title: Aspirant
description: A pen and paper RPG about adventure.
theme: just-the-docs

url: https://bombasticslacks.github.io/Aspirant/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
