name: Notify DeployAspirant

on:
  push:
    branches: ["main"]

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
        run: |
          gh api repos/bombasticSlacks/DeployAspirant/dispatches \
              --raw-field event_type=buildsite
